## Slicing 3D Tensors

In [1]:
import torch

In [2]:
x = torch.arange(18).view(3, 2, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [8]:
x[1, :, :]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

## Matrix Multiplication

In [9]:
mat_a = torch.tensor([0,3,5,5,5,2]).view(2, 3)
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [10]:
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [11]:
torch.matmul(mat_a, mat_b)

tensor([[ 29, -16],
        [ 38,   6]])

In [12]:
mat_a @ mat_b

tensor([[ 29, -16],
        [ 38,   6]])