In [1]:
list_two = list(range(1, 4))
list_three = list(range(1, 4))
list_sum = []

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])
print(list_sum)

[2, 12, 36]


In [7]:
import numpy as np

array_two = np.arange(1, 4) ** 2
array_three = np.arange(1, 4) ** 3
print(array_two + array_three)

[ 2 12 36]


In [13]:
sample_array = np.array([1, 2, 3])

In [10]:
print(np.power(np.array([1, 2, 3]), 4))

[ 1 16 81]


In [12]:
print(np.negative(np.array([1, 2, 3])))

[-1 -2 -3]


In [14]:
np.exp(sample_array)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [15]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229])

In [16]:
np.sin(sample_array)

array([0.84147098, 0.90929743, 0.14112001])

In [31]:
# arange -> array
# range - > list

import numpy as np

x = np.arange(3)
y = np.arange(3)
z = np.arange(3)

multi_array = np.array([y, z])
print(multi_array)
print(x.shape) # (3,) = (1x3)
print(multi_array.shape)



[[0 1 2]
 [0 1 2]]
(3,)
(2, 3)


In [39]:
x = np.arange(3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x,y, z], dtype = np.uint8)
print(multi_array)
print(multi_array.shape)
multi_array[1, 2]


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


5

In [40]:
print(multi_array.dtype)

uint8


In [30]:
w = np.linspace(1, 30, 100, False)
print(w)

[ 1.    1.29  1.58  1.87  2.16  2.45  2.74  3.03  3.32  3.61  3.9   4.19
  4.48  4.77  5.06  5.35  5.64  5.93  6.22  6.51  6.8   7.09  7.38  7.67
  7.96  8.25  8.54  8.83  9.12  9.41  9.7   9.99 10.28 10.57 10.86 11.15
 11.44 11.73 12.02 12.31 12.6  12.89 13.18 13.47 13.76 14.05 14.34 14.63
 14.92 15.21 15.5  15.79 16.08 16.37 16.66 16.95 17.24 17.53 17.82 18.11
 18.4  18.69 18.98 19.27 19.56 19.85 20.14 20.43 20.72 21.01 21.3  21.59
 21.88 22.17 22.46 22.75 23.04 23.33 23.62 23.91 24.2  24.49 24.78 25.07
 25.36 25.65 25.94 26.23 26.52 26.81 27.1  27.39 27.68 27.97 28.26 28.55
 28.84 29.13 29.42 29.71]


In [27]:
b = np.arange(1, 30)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


## slicing

In [42]:
import numpy as np

x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [46]:
x[2:7]

array([3, 4, 5, 6, 7])

## reshaping

In [52]:
import numpy as np

x = np.arange(18).reshape(3, 3, 2) # unknown dimension = -1
print(x) # (2, 3, 3) : 2 blocks data, each one has 3 rows and 3 columns

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [56]:
x = np.arange(18).reshape(3, 2, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [60]:

x[1,:, :]
# x[1, ...]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
x[:, 0, 0]


array([ 0,  6, 12])

In [62]:
x[1, :, : :2]

array([[ 6,  8],
       [ 9, 11]])

In [65]:
comparison_operation = x > 5
print(comparison_operation)

print(x[comparison_operation])

print(x[x>5])

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
[ 6  7  8  9 10 11 12 13 14 15 16 17]
[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [66]:
x.max()

17

In [67]:
x.min()

0

## manipulating

In [73]:
import numpy as np

x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [72]:
ravelled_array = x.ravel() # return a origin of view
ravelled_array[2] = 100000
print(ravelled_array)
print(x)

[     0      1 100000      3      4      5      6      7      8]
[[     0      1 100000]
 [     3      4      5]
 [     6      7      8]]


In [74]:
flattened_array = x.flatten() # returns a copy
flattened_array[2] = 100000
print(flattened_array)
print(x)

[     0      1 100000      3      4      5      6      7      8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [75]:
y = np.arange(9)
y.shape = [3,3]
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [77]:
print(y.transpose())
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [78]:
print(np.resize(y, (6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [82]:
print(np.zeros((2,3), dtype=int))

[[0 0 0]
 [0 0 0]]


In [83]:
print(np.ones((2,3), dtype=int))

[[1 1 1]
 [1 1 1]]


In [86]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [87]:
np.random.rand(4, 4)

array([[0.84845895, 0.85842553, 0.00384615, 0.78734282],
       [0.29315661, 0.08034357, 0.93735959, 0.53706689],
       [0.85336969, 0.89887354, 0.78423741, 0.20118578],
       [0.24449273, 0.42585085, 0.14658988, 0.04420284]])

## Matrix Multiplication

In [90]:
import numpy as np

mat_a = np.array([0,3,5,5,5,2]).reshape(2,3)
mat_a

matrix([[0, 3, 5],
        [5, 5, 2]])

In [91]:
mat_b = np.array([3,4,3,-2,4,-2]).reshape(3,2)
mat_b

matrix([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [92]:
mat_a * mat_b

matrix([[ 29, -16],
        [ 38,   6]])

In [93]:
product = np.matmul(mat_a, mat_b)
product

matrix([[ 29, -16],
        [ 38,   6]])

In [94]:
mat_a @ mat_b

matrix([[ 29, -16],
        [ 38,   6]])

## Stack

In [102]:
import numpy as np

x = np.arange(4).reshape(2, 2)
print(x)
print(x.shape)

[[0 1]
 [2 3]]
(2, 2)


In [116]:
y = np.arange(8).reshape(2, 4)
print(y)

[[0 1 2 3]
 [4 5 6 7]]


In [108]:
z = np.hstack((x, y))
print(z)
print(z.shape)

[[0 1 0 1 2 3]
 [2 3 4 5 6 7]]
(2, 6)


In [110]:
y = np.arange(8).reshape(4, 2)
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [111]:
z = np.vstack((x, y))
print(z)
print(z.shape)

[[0 1]
 [2 3]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]
(6, 2)


In [115]:
w = np.concatenate((x,y), axis=0)
print(w)

[[0 1]
 [2 3]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]


In [117]:
w = np.concatenate((x,y), axis=1)
print(w)

[[0 1 0 1 2 3]
 [2 3 4 5 6 7]]


In [118]:
z = np.hstack((x, y))

In [119]:
print(z == w)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [120]:
y = x * 2
print(y)

[[0 2]
 [4 6]]


In [121]:
depth_stack = np.dstack((x, y))
print(depth_stack) # (2,2,1) + (2,2,1) = (2,2,2)

[[[0 0]
  [1 2]]

 [[2 4]
  [3 6]]]


In [122]:
print(depth_stack.shape)

(2, 2, 2)


In [132]:
print(np.column_stack((x, y))== np.hstack((x,y)))

[[ True  True  True  True]
 [ True  True  True  True]]


In [131]:
print(np.row_stack((x, y)) == np.vstack((x,y)))

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
