In [1]:
import numpy as np
import torch

In [5]:
t = np.array([0., 1., 2.])
print(t)

[0. 1. 2.]


In [6]:
print(t.ndim)
print(t.shape)

1
(3,)


In [9]:
print(t[0])
print(t[1])
print(t[-2])

0.0
1.0
1.0


In [11]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [20]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-5:-1])
print(t[2:-2])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor([2., 3., 4., 5.])
tensor([2., 3., 4.])


In [22]:
t = torch.FloatTensor([[1., 2., 3., 4.],
                       [5., 6., 7., 8.]
                       ])

In [23]:
t.size()

torch.Size([2, 4])

In [27]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [2]:
t = torch.FloatTensor([[1, 2,3], [4,5, 6]])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [3]:
print(t.mean())
print(t.mean(dim=0)) # column 평균
print(t.mean(dim=1)) # row 평균
print(t.mean(dim=-1)) # last dimension 평균 

tensor(3.5000)
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor([2., 5.])


In [4]:
print(t.sum())
print(t.sum(dim=0)) # column 합계
print(t.sum(dim=1)) # row 합계
print(t.sum(dim=-1)) # last dimension 합계 

tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor([ 6., 15.])


In [5]:
print(t.max())

tensor(6.)


In [34]:
print(t.argmax())

tensor(5)


In [8]:
tf = torch.FloatTensor([[0], [1], [2]])
print(tf)
print(tf.shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [9]:
tf=tf.squeeze()
print(tf)
print(tf.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [20]:
ft = torch.Tensor([[0, 1, 2], [3,4,5]])
print(ft)
print(ft.shape)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
torch.Size([2, 3])


In [21]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[[0., 1., 2.],
         [3., 4., 5.]]])
torch.Size([1, 2, 3])


In [24]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[[0., 1., 2.]],

        [[3., 4., 5.]]])
torch.Size([2, 1, 3])


In [10]:
# Type Casting
lt = torch.LongTensor([1,2,3,4]) # Long = 64bit = 2^14
print(lt)

tensor([1, 2, 3, 4])


In [11]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [12]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [ ]:
# Byte = 8 BIt 
# 1 Bit = 0 or 1
# True = 1
# False = 0
# uint8 = u=unsined => can be only positive value (0 ~ 255) (= 2^8 - 1)


In [25]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [27]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [28]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [29]:
print(torch.ones_like(x)) # torch.ones_like((2,3))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [34]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

In [35]:
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [36]:
x = torch.FloatTensor([[1, 2,3 ], [3, 4,5]])

In [37]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]])
tensor([[1., 2., 3.],
        [3., 4., 5.]])
tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]])
tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]])


In [41]:
x.view(1,-1)

tensor([[ 2.,  4.,  6.,  6.,  8., 10.]])

In [39]:
x

tensor([[ 2.,  4.,  6.],
        [ 6.,  8., 10.]])