In [13]:
import torch
import numpy as np

In [6]:
v = torch.tensor([1,2,3,4,5,6])
print(v[1:4])

tensor([2, 3, 4])


In [9]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.size())

torch.Size([6])


In [11]:
v.view(3, 2) # reshape

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [12]:
v.view(3, -1) # -1을 이용하면 사이즈를 고려하지 않아도 된다.

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [15]:
a = np.array([1, 2, 3, 4, 5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)
<built-in method type of Tensor object at 0x00000176E01A3C18>


In [16]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
